# Generated by Django 4.2.1 on 2023-05-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_filmekle_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinemaEkle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=300)),
                ('gold_class', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='filmekle',
            options={'ordering': ['title']},
        ),
    ]
