# Generated by Django 4.2.1 on 2023-05-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_sinemaekle_alter_filmekle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sinemaekle',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='sinemaekle',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
