# Generated by Django 4.2.1 on 2023-05-07 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_filmekle_sinema'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonEkle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('salon_id', models.IntegerField()),
            ],
            options={
                'ordering': ['salon_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='filmekle',
            options={},
        ),
        migrations.RemoveField(
            model_name='filmekle',
            name='sinema',
        ),
        migrations.AddField(
            model_name='sinemaekle',
            name='filmler',
            field=models.ManyToManyField(related_name='sinemalar', to='movie_app.filmekle'),
        ),
        migrations.CreateModel(
            name='SeansEkle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('saat', models.TimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seanslar', to='movie_app.filmekle')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seanslar', to='movie_app.salonekle')),
            ],
            options={
                'ordering': ['saat'],
            },
        ),
        migrations.AddField(
            model_name='salonekle',
            name='sinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salonlar', to='movie_app.sinemaekle'),
        ),
    ]
