# Generated by Django 4.2.1 on 2023-05-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_genre_alter_filmekle_options_alter_seansekle_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seansekle',
            name='id',
        ),
        migrations.AddField(
            model_name='seansekle',
            name='seans_id',
            field=models.PositiveIntegerField(default=5, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
