# Generated by Django 4.2.1 on 2023-05-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_remove_seansekle_id_seansekle_seans_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seansekle',
            name='id',
            field=models.BigAutoField(auto_created=True, default=5, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seansekle',
            name='seans_id',
            field=models.IntegerField(),
        ),
    ]
