# Generated by Django 4.2.1 on 2023-05-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_seansekle_id_alter_seansekle_seans_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seansekle',
            name='id',
        ),
        migrations.AlterField(
            model_name='seansekle',
            name='seans_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
