# Generated by Django 4.2.1 on 2023-05-18 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0012_remove_bilet_bilet_turu_remove_bilet_koltuk_numarasi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilet',
            name='adet',
        ),
        migrations.RemoveField(
            model_name='bilet',
            name='bilet_tipi',
        ),
        migrations.RemoveField(
            model_name='bilet',
            name='fiyat',
        ),
        migrations.AddField(
            model_name='bilet',
            name='bilet_turu',
            field=models.CharField(choices=[('Tam', 'Tam Bilet'), ('Öğrenci', 'Öğrenci Bilet')], default='Tam', max_length=10),
        ),
        migrations.AddField(
            model_name='bilet',
            name='koltuk_numarasi',
            field=models.CharField(default='default_value', max_length=10),
        ),
        migrations.AddField(
            model_name='bilet',
            name='ogrenci_bilet_fiyati',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bilet',
            name='tam_bilet_fiyati',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bilet',
            name='zaman',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
