# Generated by Django 4.2.1 on 2023-05-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0016_alter_bilet_zaman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilet',
            name='zaman',
            field=models.DateTimeField(default='2023-05-18T17:08:44.091102+00:00'),
        ),
    ]
