# Generated by Django 4.2.1 on 2023-05-18 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0018_remove_bilet_zaman'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilet',
            name='zaman',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
