# Generated by Django 4.2.1 on 2023-05-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0021_bilet_ad_bilet_email_bilet_odeme_yapildi_bilet_soyad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilet',
            name='ogrenci_bilet_fiyati',
            field=models.DecimalField(decimal_places=2, default=75, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bilet',
            name='tam_bilet_fiyati',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
    ]
