# Generated by Django 4.2.1 on 2023-05-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0023_alter_bilet_ogrenci_bilet_fiyati_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilet',
            name='ogrenci_bilet_fiyati',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bilet',
            name='tam_bilet_fiyati',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
