# Generated by Django 4.2.1 on 2023-05-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0025_alter_bilet_ogrenci_bilet_fiyati_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilet',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='bilet',
            name='soyad',
        ),
        migrations.AddField(
            model_name='bilet',
            name='ad_soyad',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
    ]
