# Generated by Django 4.2.1 on 2023-05-20 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0027_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.PositiveSmallIntegerField(unique=True)),
                ('row_no', models.PositiveSmallIntegerField()),
                ('seat_name', models.CharField(max_length=3, unique=True)),
                ('booked_by', models.CharField(blank=True, max_length=200)),
                ('seans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seats', to='movie_app.seansekle')),
            ],
            options={
                'verbose_name_plural': 'Seats',
            },
        ),
    ]
