# Generated by Django 4.2.1 on 2023-05-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0029_delete_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('color', models.CharField(max_length=50)),
                ('is_selectable', models.BooleanField(default=True)),
            ],
        ),
    ]
