# Generated by Django 4.2.1 on 2023-05-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0031_remove_seat_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='satir',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='sutun',
            field=models.PositiveIntegerField(default=7),
            preserve_default=False,
        ),
    ]
