# Generated by Django 4.2.1 on 2023-05-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0032_seat_satir_seat_sutun'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilet',
            name='iade_edildi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bilet',
            name='iade_tutari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
