# Generated by Django 4.2.1 on 2023-05-21 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_app', '0033_bilet_iade_edildi_bilet_iade_tutari'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilet',
            name='kullanici',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biletler', to=settings.AUTH_USER_MODEL),
        ),
    ]
