# Generated by Django 4.2.1 on 2023-05-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0034_bilet_kullanici'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilet',
            name='kullanici',
        ),
    ]
